import "~/styles/globals.css";

import { type Metadata } from "next";
import { gambarino, kalam, britney } from "~/fonts";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata: Metadata = {
  title: "Interactive Calendar Component",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${gambarino.className} ${kalam.variable} ${britney.variable}`}
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
